# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: store.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'store.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstore.proto\x12\x05store\"H\n\x12SaveMessageRequest\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"&\n\x13SaveMessageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\"\n\x11GetHistoryRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\"A\n\x0b\x43hatMessage\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\":\n\x12GetHistoryResponse\x12$\n\x08messages\x18\x01 \x03(\x0b\x32\x12.store.ChatMessage2\x97\x01\n\x0cStoreService\x12\x44\n\x0bSaveMessage\x12\x19.store.SaveMessageRequest\x1a\x1a.store.SaveMessageResponse\x12\x41\n\nGetHistory\x12\x18.store.GetHistoryRequest\x1a\x19.store.GetHistoryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'store_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SAVEMESSAGEREQUEST']._serialized_start=22
  _globals['_SAVEMESSAGEREQUEST']._serialized_end=94
  _globals['_SAVEMESSAGERESPONSE']._serialized_start=96
  _globals['_SAVEMESSAGERESPONSE']._serialized_end=134
  _globals['_GETHISTORYREQUEST']._serialized_start=136
  _globals['_GETHISTORYREQUEST']._serialized_end=170
  _globals['_CHATMESSAGE']._serialized_start=172
  _globals['_CHATMESSAGE']._serialized_end=237
  _globals['_GETHISTORYRESPONSE']._serialized_start=239
  _globals['_GETHISTORYRESPONSE']._serialized_end=297
  _globals['_STORESERVICE']._serialized_start=300
  _globals['_STORESERVICE']._serialized_end=451
# @@protoc_insertion_point(module_scope)
